### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/releases#28]
Would be nice to have build results in pull requests. :smiley:

**Comment by billbogaiv** [comment]
I can work setting this up. Since we're aiming for cross-platform, I'll start with Travis CI. We can always add AppVeyor later—similar to [aspnet/dnx](/aspnet/dnx) setup.

**Comment by khalidabuhakmeh** [comment]
Cool :thumbsup:

**Comment by billbogaiv** [comment]
@kendaleiv: everything is in place for running and reporting builds. Please close if you are satisfied.

**Comment by khalidabuhakmeh** [comment]
https://travis-ci.org/ritterim/releases
