### ISSUE TITLE
Remove user pictures? Or, add additional pictures for involvement?

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/releases#36]
Thoughts? Are they adding value? I assume it indicates who published the release. But, at least in our case, is this valuable information for our users to know?

Or, is it intended to give some _personality_ to the release?
## Suggested enhancement

If we could have the avatar of **everyone's** picture who had GitHub activity related to that releases, rather than a single individual, that would be awesome.

**Comment by khalidabuhakmeh** [comment]
I think you meant **everyone** right?

**Comment by kendaleiv** [comment]
Yes, fixed. Thanks.

**Comment by billbogaiv** [comment]
There does not appear to be a way to get committers within a release: https://developer.github.com/v3/repos/releases/

**Comment by kendaleiv** [comment]
So, our options are:
- Make GitHub API requests to figure it out (perhaps walking the **master** branch commits?)
- Clone the repos and perform the operations. If we did this, we'd probably want to avoid cloning every single time and save the repo code long term. This could also bloat the size of this application's file system footprint considerably.

This would be a great addition. But, if there's not a good/feasible way to do it at this time -- it might not be worth it.

**Comment by billbogaiv** [comment]
It's a limitation of the API since commit-related data is not returned for releases, so we don't know beginning and end of commits between releases.

**Comment by gep13** [comment]
@kendaleiv @billboga isn't this where the `Compare` API would come it.  We use this in the [GitReleaseManager](https://github.com/GitTools/GitReleaseManager) tool to generate Release Notes similar to the following:

https://github.com/chocolatey/ChocolateyGUI/releases/tag/0.13.2

Which takes you through to here:

https://github.com/chocolatey/chocolateygui/compare/0.13.1...0.13.2

Through the GitHub API, and Octokit in my case, you can then do:

![image](https://cloud.githubusercontent.com/assets/1271146/12114147/67dad012-b39f-11e5-9f7f-5e2ec3828641.png)

To get information about each Commit.  Here I am using tags to do the comparison, but I "think" it is possible with SHA's also.  Hope that helps!

**Comment by khalidabuhakmeh** [comment]
Oh cool, didn't know that exists. We will have to look at that.

**Comment by gep13** [comment]
> @khalidabuhakmeh said..
> Oh cool, didn't know that exists. We will have to look at that.

:+1:

**Comment by kendaleiv** [comment]
Awesome, this now looks possible and feasible (without having to clone the repo or similar) by using the compare API!

**Comment by kendaleiv** [comment]
I started working on this, but ran into an issue identifying the previous release, given a release. The only way I've found the current GitHub API offerings is traversing through all of the releases start to finish until we find the target release -- and then the next one is the previous release, if any previous releases exist.
- This approach is limited to 250 commits per release.
- This feature seems potentially too expensive for what it is.

The incomplete work so far is committed and pushed. See https://github.com/ritterim/releases/compare/master...kendaleiv:issue-36.

**Comment by kendaleiv** [comment]
I'm going to close this. We can revisit it later, if necessary / we want to.

**Comment by gep13** [comment]
> @kendaleiv said...
> The only way I've found the current GitHub API offerings is traversing through all of the releases start to finish until we find the target release

Yes, this is essentially what we have had to do (albeit using milestones):

https://github.com/GitTools/GitReleaseManager/blob/f1f6947c773432ef825b745fcde254995d5d3b2a/Source/GitReleaseManager/ReleaseNotesBuilder.cs#L128

**Comment by kendaleiv** [comment]
@gep13: Thanks! Good to know I'm not missing something.
